version: '3.8'

services:
  sqlserver:
    image: mysql
    # restart: always
    env_file: docker.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - 3307:3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    links:
      - sqlserver
    ports:
      - 3000:3000
    # restart: always